### ISSUE TITLE
Missing schema error in flask app due to favicon.ico

### ISSUE THREAD

**Issue by PaulSayantan** [belikesayantan/amzn-price-tracker#1]
recieving 500 internal server error
Here, is the error log
```bash
127.0.0.1 - - [21/Sep/2020 15:44:33] "GET /https://www.amazon.in/Vivo-Glacier-Storage-Additional-Exchange/dp/B07XD1ZFJ9?ref_=Oct_DLandingS_D_746071db_61&smid=A14CZOWI0VEHLG HTTP/1.1" 200 -
127.0.0.1 - - [21/Sep/2020 15:44:33] "GET /favicon.ico HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sayantan/Desktop/workspace/github/wle/app.py", line 81, in scraper
    return jsonify(Item=scraping(url))
  File "/home/sayantan/Desktop/workspace/github/wle/app.py", line 18, in scraping
    res = requests.get(url, headers=headers)
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/home/sayantan/.local/share/virtualenvs/wle-6eHkG7da/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'favicon.ico': No schema supplied. Perhaps you meant http://favicon.ico?
```

**Comment by PaulSayantan** [comment]
issue resolved by turning off the debugging by flask `app.run()`
